name: manage-azure-policy-71bfa08b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
  push:
    paths:
#      - 'policy/initiatives/NIST_SP_800-171_Rev._2_03055927-78bd-4236-86c0-f36125a10dc9/**'
#      - 'policy/initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**'
#      - 'policy/initiatives/Configure_Linux_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_118f04da-0375-44d1-84e3-0fd9e1849403/**'
#      - 'policy/initiatives/NIST_SP_800-53_Rev._5_179d1daa-458f-4e47-8086-2a68d0d6c38f/**'
#      - 'policy/initiatives/Deploy_prerequisites_to_enable_Guest_Configuration_policies_on_virtual_machines_12794019-7a00-42cf-95c2-882eed337cc8/**'
#      - 'policy/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**'
      - 'policy/initiatives/Azure_Security_Benchmark_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**'
      - 'policy/initiatives/UK_OFFICIAL_and_UK_NHS_3937f550-eedd-4639-9c5e-294358be442e/**'
      - 'policy/initiatives/_Preview_Configure_Azure_Defender_for_SQL_agents_on_virtual_machines_39a366e6-fdde-4f41-bbf8-3757f46d1611/**'
#      - 'policy/initiatives/_Preview_SWIFT_CSP-CSCF_v2020_3e0c67fc-8c7c-406c-89bd-6b6bdc986a22/**'
#      - 'policy/initiatives/Kubernetes_cluster_pod_security_restricted_standards_for_Linux-based_workloads_42b8ef37-b724-4e24-bbc8-7a7708edfe00/**'
#      - 'policy/initiatives/PCI_v3.2.1_2018_496eeda9-8f2f-4d5e-8dfd-204f0a92ed41/**'
#      - 'policy/initiatives/Enable_Azure_Monitor_for_VMs_55f3eceb-5573-4f18-9695-226972c6d74a/**'
#      - 'policy/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0_612b5213-9160-4969-8578-1518bd2a000c/**'
#      - 'policy/initiatives/Flow_logs_should_be_configured_and_enabled_for_every_network_security_group_62329546-775b-4a3d-a4cb-eb4bb990d2c0/**'
#      - 'policy/initiatives/Enable_Azure_Monitor_for_Virtual_Machine_Scale_Sets_75714362-cae7-409e-9b99-a8e5075b7fad/**'
#      - 'policy/initiatives/ISO_27001_2013_89c6cddc-1c73-4ac1-b19c-54d1a15a42f2/**'
#      - 'policy/initiatives/_Preview_Motion_Picture_Association_of_America_(MPAA)_92646f03-e39d-47a9-9e24-58d60ef49af8/**'
#      - 'policy/initiatives/Configure_Windows_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_9575b8b7-78ab-4281-b53b-d3c1ace2260b/**'
#      - 'policy/initiatives/Configure_Azure_Defender_to_be_enabled_on_SQL_Servers_and_SQL_Managed_Instances_9cb3cc7a-b39b-4b82-bc89-e5a5d9ff7b97/**'
#      - 'policy/initiatives/_Preview_Configure_machines_to_automatically_install_the_Azure_Monitor_and_Azure_Security_agents_on_virtual_machines_a15f3269-2e10-458c-87a4-d5989e678a73/**'
#      - 'policy/initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**'
#      - 'policy/initiatives/Configure_Advanced_Threat_Protection_to_be_enabled_on_open-source_relational_databases_e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e/**'
#      - 'policy/initiatives/NIST_SP_800-53_Rev._4_cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f/**'
#      - 'policy/initiatives/Enable_Azure_Cosmos_DB_throughput_policy_cb5e1e90-7c33-491c-a15b-24885c915752/**'
#      - 'policy/initiatives/_Preview_Windows_machines_should_meet_requirements_for_the_Azure_compute_security_baseline_be7a78aa-3e10-4153-a5fd-8c6506dbc821/**'
#      - 'policy/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**'
#      - 'policy/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'policy/policies/Vulnerability_assessment_should_be_enabled_on_your_Synapse_workspaces_0049a6b3-a662-4f3e-8635-39cf44ace45a/**'
#      - 'policy/policies/_Preview_Configure_VMSS_created_with_Shared_Image_Gallery_images_to_install_the_Guest_Attestation_extension_009259b0-12e8-42c9-94e7-7af86aa58d13/**'
#      - 'policy/policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**'
#      - 'policy/policies/Private_endpoint_connections_on_Batch_accounts_should_be_enabled_009a0c92-f5b4-4776-9b66-4ed2b4775563/**'
#      - 'policy/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'policy/policies/_Preview_Azure_Security_agent_should_be_installed_on_your_Windows_Arc_machines_0367cfc4-90b3-46ba-a8a6-ddd5d3514878/**'
#      - 'policy/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**'
#      - 'policy/policies/Azure_Kubernetes_Service_Private_Clusters_should_be_enabled_040732e8-d947-40b8-95d6-854c95024bf8/**'
#      - 'policy/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**'
#      - 'policy/policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**'
#      - 'policy/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**'
#      - 'policy/policies/_Preview_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**'
#      - 'policy/policies/Shared_dashboards_should_not_have_markdown_tiles_with_inline_content_04c655fe-0ac7-48ae-9a32-3a2e208c7624/**'
#      - 'policy/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**'
#      - 'policy/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**'
#      - 'policy/policies/Deploy_Log_Analytics_extension_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**'
#      - 'policy/policies/Azure_Web_Application_Firewall_should_be_enabled_for_Azure_Front_Door_entry-points_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**'
#      - 'policy/policies/Private_endpoint_should_be_enabled_for_PostgreSQL_servers_0564d078-92f5-4f97-8398-b9f58a51f70b/**'
#      - 'policy/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**'
#      - 'policy/policies/Resource_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**'
#      - 'policy/policies/Configure_Azure_File_Sync_to_use_private_DNS_zones_06695360-db88-47f6-b976-7500d4297475/**'
#      - 'policy/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**'
#      - 'policy/policies/Cognitive_Services_accounts_should_disable_public_network_access_0725b4dd-7e76-479c-a735-68e7ee23d5ca/**'
#      - 'policy/policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**'
#      - 'policy/policies/Deploy_-_Configure_Log_Analytics_extension_to_be_enabled_on_Windows_virtual_machines_0868462e-646c-4fe3-9ced-a733534b6a2c/**'
#      - 'policy/policies/Audit_Windows_machines_on_which_the_DSC_configuration_is_not_compliant_08a2f2d2-94b2-4a7b-aa3b-bb3f523ee6fd/**'
#      - 'policy/policies/Azure_Edge_Hardware_Center_devices_should_have_double_encryption_support_enabled_08a6b96f-576e-47a2-8511-119a212d344d/**'
#      - 'policy/policies/Configure_Data_Factories_to_disable_public_network_access_08b1442b-7789-4130-8506-4f99a97226a7/**'
#      - 'policy/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**'
#      - 'policy/policies/Adaptive_network_hardening_recommendations_should_be_applied_on_internet_facing_virtual_machines_08e6af2d-db70-460a-bfe9-d5bd474ba9d6/**'
#      - 'policy/policies/There_should_be_more_than_one_owner_assigned_to_your_subscription_09024ccc-0c5f-475e-9457-b7c0d9ed487b/**'
#      - 'policy/policies/Virtual_machines_should_encrypt_temp_disks,_caches,_and_data_flows_between_Compute_and_Storage_resources_0961003e-5a0a-4549-abde-af6a37f2724d/**'
#      - 'policy/policies/Configure_backup_on_virtual_machines_without_a_given_tag_to_an_existing_recovery_services_vault_in_the_same_location_09ce66bc-1220-4153-8104-e3f51c936913/**'
#      - 'policy/policies/Private_endpoint_should_be_enabled_for_MariaDB_servers_0a1302fb-a631-4106-9753-f3d494733990/**'
#      - 'policy/policies/Azure_Policy_Add-on_for_Kubernetes_service_(AKS)_should_be_installed_and_enabled_on_your_clusters_0a15ec92-a229-4763-bb14-0ea34a568f8d/**'
#      - 'policy/policies/SQL_servers_should_use_customer-managed_keys_to_encrypt_data_at_rest_0a370ff3-6cab-4e85-8995-295fd854c5b8/**'
#      - 'policy/policies/Audit_resource_location_matches_resource_group_location_0a914e76-4921-4c19-b460-a2d36003525a/**'
#      - 'policy/policies/Azure_Defender_for_open-source_relational_databases_should_be_enabled_0a9fbe0d-c5c4-4da8-87d8-f4fd77338835/**'
#      - 'policy/policies/Azure_Container_Instance_container_group_should_use_customer-managed_key_for_encryption_0aa61e00-0a01-4a3c-9945-e93cffedf0e6/**'
#      - 'policy/policies/_Preview_Configure_Azure_Arc_enabled_Kubernetes_clusters_to_install_the_Azure_Policy_extension_0adc5395-9169-4b9b-8687-af838d69410a/**'
#      - 'policy/policies/Configure_Azure_Web_PubSub_Service_to_use_private_DNS_zones_0b026355-49cb-467b-8ac4-f777874e175a/**'
#      - 'policy/policies/Email_notification_to_subscription_owner_for_high_severity_alerts_should_be_enabled_0b15565f-aa9e-48ba-8619-45960f2c314d/**'
#      - .github/workflows/manage-azure-policy-71bfa08b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_71bfa08b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policy/initiatives/NIST_SP_800-171_Rev._2_03055927-78bd-4236-86c0-f36125a10dc9/**
          policy/initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**
          policy/initiatives/Configure_Linux_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_118f04da-0375-44d1-84e3-0fd9e1849403/**
          policy/initiatives/NIST_SP_800-53_Rev._5_179d1daa-458f-4e47-8086-2a68d0d6c38f/**
          policy/initiatives/Deploy_prerequisites_to_enable_Guest_Configuration_policies_on_virtual_machines_12794019-7a00-42cf-95c2-882eed337cc8/**
          policy/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**
          policy/initiatives/Azure_Security_Benchmark_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**
          policy/initiatives/UK_OFFICIAL_and_UK_NHS_3937f550-eedd-4639-9c5e-294358be442e/**
          policy/initiatives/_Preview_Configure_Azure_Defender_for_SQL_agents_on_virtual_machines_39a366e6-fdde-4f41-bbf8-3757f46d1611/**
          policy/initiatives/_Preview_SWIFT_CSP-CSCF_v2020_3e0c67fc-8c7c-406c-89bd-6b6bdc986a22/**
          policy/initiatives/Kubernetes_cluster_pod_security_restricted_standards_for_Linux-based_workloads_42b8ef37-b724-4e24-bbc8-7a7708edfe00/**
          policy/initiatives/PCI_v3.2.1_2018_496eeda9-8f2f-4d5e-8dfd-204f0a92ed41/**
          policy/initiatives/Enable_Azure_Monitor_for_VMs_55f3eceb-5573-4f18-9695-226972c6d74a/**
          policy/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0_612b5213-9160-4969-8578-1518bd2a000c/**
          policy/initiatives/Flow_logs_should_be_configured_and_enabled_for_every_network_security_group_62329546-775b-4a3d-a4cb-eb4bb990d2c0/**
          policy/initiatives/Enable_Azure_Monitor_for_Virtual_Machine_Scale_Sets_75714362-cae7-409e-9b99-a8e5075b7fad/**
          policy/initiatives/ISO_27001_2013_89c6cddc-1c73-4ac1-b19c-54d1a15a42f2/**
          policy/initiatives/_Preview_Motion_Picture_Association_of_America_(MPAA)_92646f03-e39d-47a9-9e24-58d60ef49af8/**
          policy/initiatives/Configure_Windows_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_9575b8b7-78ab-4281-b53b-d3c1ace2260b/**
          policy/initiatives/Configure_Azure_Defender_to_be_enabled_on_SQL_Servers_and_SQL_Managed_Instances_9cb3cc7a-b39b-4b82-bc89-e5a5d9ff7b97/**
          policy/initiatives/_Preview_Configure_machines_to_automatically_install_the_Azure_Monitor_and_Azure_Security_agents_on_virtual_machines_a15f3269-2e10-458c-87a4-d5989e678a73/**
          policy/initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**
          policy/initiatives/Configure_Advanced_Threat_Protection_to_be_enabled_on_open-source_relational_databases_e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e/**
          policy/initiatives/NIST_SP_800-53_Rev._4_cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f/**
          policy/initiatives/Enable_Azure_Cosmos_DB_throughput_policy_cb5e1e90-7c33-491c-a15b-24885c915752/**
          policy/initiatives/_Preview_Windows_machines_should_meet_requirements_for_the_Azure_compute_security_baseline_be7a78aa-3e10-4153-a5fd-8c6506dbc821/**
          policy/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**
          policy/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          policy/policies/Vulnerability_assessment_should_be_enabled_on_your_Synapse_workspaces_0049a6b3-a662-4f3e-8635-39cf44ace45a/**
          policy/policies/_Preview_Configure_VMSS_created_with_Shared_Image_Gallery_images_to_install_the_Guest_Attestation_extension_009259b0-12e8-42c9-94e7-7af86aa58d13/**
          policy/policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**
          policy/policies/Private_endpoint_connections_on_Batch_accounts_should_be_enabled_009a0c92-f5b4-4776-9b66-4ed2b4775563/**
          policy/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          policy/policies/_Preview_Azure_Security_agent_should_be_installed_on_your_Windows_Arc_machines_0367cfc4-90b3-46ba-a8a6-ddd5d3514878/**
          policy/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**
          policy/policies/Azure_Kubernetes_Service_Private_Clusters_should_be_enabled_040732e8-d947-40b8-95d6-854c95024bf8/**
          policy/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**
          policy/policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**
          policy/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**
          policy/policies/_Preview_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**
          policy/policies/Shared_dashboards_should_not_have_markdown_tiles_with_inline_content_04c655fe-0ac7-48ae-9a32-3a2e208c7624/**
          policy/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**
          policy/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**
          policy/policies/Deploy_Log_Analytics_extension_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**
          policy/policies/Azure_Web_Application_Firewall_should_be_enabled_for_Azure_Front_Door_entry-points_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**
          policy/policies/Private_endpoint_should_be_enabled_for_PostgreSQL_servers_0564d078-92f5-4f97-8398-b9f58a51f70b/**
          policy/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**
          policy/policies/Resource_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**
          policy/policies/Configure_Azure_File_Sync_to_use_private_DNS_zones_06695360-db88-47f6-b976-7500d4297475/**
          policy/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**
          policy/policies/Cognitive_Services_accounts_should_disable_public_network_access_0725b4dd-7e76-479c-a735-68e7ee23d5ca/**
          policy/policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**
          policy/policies/Deploy_-_Configure_Log_Analytics_extension_to_be_enabled_on_Windows_virtual_machines_0868462e-646c-4fe3-9ced-a733534b6a2c/**
          policy/policies/Audit_Windows_machines_on_which_the_DSC_configuration_is_not_compliant_08a2f2d2-94b2-4a7b-aa3b-bb3f523ee6fd/**
          policy/policies/Azure_Edge_Hardware_Center_devices_should_have_double_encryption_support_enabled_08a6b96f-576e-47a2-8511-119a212d344d/**
          policy/policies/Configure_Data_Factories_to_disable_public_network_access_08b1442b-7789-4130-8506-4f99a97226a7/**
          policy/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**
          policy/policies/Adaptive_network_hardening_recommendations_should_be_applied_on_internet_facing_virtual_machines_08e6af2d-db70-460a-bfe9-d5bd474ba9d6/**
          policy/policies/There_should_be_more_than_one_owner_assigned_to_your_subscription_09024ccc-0c5f-475e-9457-b7c0d9ed487b/**
          policy/policies/Virtual_machines_should_encrypt_temp_disks,_caches,_and_data_flows_between_Compute_and_Storage_resources_0961003e-5a0a-4549-abde-af6a37f2724d/**
          policy/policies/Configure_backup_on_virtual_machines_without_a_given_tag_to_an_existing_recovery_services_vault_in_the_same_location_09ce66bc-1220-4153-8104-e3f51c936913/**
          policy/policies/Private_endpoint_should_be_enabled_for_MariaDB_servers_0a1302fb-a631-4106-9753-f3d494733990/**
          policy/policies/Azure_Policy_Add-on_for_Kubernetes_service_(AKS)_should_be_installed_and_enabled_on_your_clusters_0a15ec92-a229-4763-bb14-0ea34a568f8d/**
          policy/policies/SQL_servers_should_use_customer-managed_keys_to_encrypt_data_at_rest_0a370ff3-6cab-4e85-8995-295fd854c5b8/**
          policy/policies/Audit_resource_location_matches_resource_group_location_0a914e76-4921-4c19-b460-a2d36003525a/**
          policy/policies/Azure_Defender_for_open-source_relational_databases_should_be_enabled_0a9fbe0d-c5c4-4da8-87d8-f4fd77338835/**
          policy/policies/Azure_Container_Instance_container_group_should_use_customer-managed_key_for_encryption_0aa61e00-0a01-4a3c-9945-e93cffedf0e6/**
          policy/policies/_Preview_Configure_Azure_Arc_enabled_Kubernetes_clusters_to_install_the_Azure_Policy_extension_0adc5395-9169-4b9b-8687-af838d69410a/**
          policy/policies/Configure_Azure_Web_PubSub_Service_to_use_private_DNS_zones_0b026355-49cb-467b-8ac4-f777874e175a/**
          policy/policies/Email_notification_to_subscription_owner_for_high_severity_alerts_should_be_enabled_0b15565f-aa9e-48ba-8619-45960f2c314d/**
